cadvisor:
 image: google/cadvisor:latest
 restart: always
 volumes:
 - /:/rootfs:ro
 - /var/run:/var/run:rw
 - /sys:/sys:ro
 - /var/lib/docker/:/var/lib/docker:ro

proxy:
 build: ./proxy/
 restart: always
 links:
 - cadvisor:cadvisor
 ports:
 - "80:80"

monitor:
 build: ./monitor/
 restart: always
 volumes:
 - data/status/:/data/status/:rw
 - /var/run/docker.sock:/var/run/docker.sock

status:
 build: ./status/
 restart: always
 volumes_from:
 - monitor
 ports:
 - "81:80"

counter:
 build: ./counter/
 restart: always
 ports:
 - "82:8080"
 volumes:
 - data/obj/:/obj/:rw

