FROM ubuntu:14.04

RUN apt-get update -qqy && apt-get -qy install vim

RUN echo hello world

RUN touch /helloworld.txt

RUN ps -ef > /helloworld.txt

MAINTAINER Maciej Jablonski <maciej.jablonski.1985@gmail.com
